-- Buat pengguna premium baru
INSERT INTO users (
  id,
  name,
  username,
  email,
  created_at,
  updated_at,
  is_premium,
  premium_expires_at,
  numeric_id,
  avatar_url,
  bio,
  instagram_url,
  facebook_url,
  linkedin_url,
  twitter_url,
  tiktok_url,
  allow_public_replies,
  phone_number,
  notification_channel,
  whatsapp_notifications,
  telegram_notifications
) VALUES (
  gen_random_uuid(),
  'Anita Wijaya',
  'anitawijaya',
  'anita.wijaya.sample@example.com',
  NOW(),
  NOW(),
  TRUE,
  NOW() + INTERVAL '1 year',
  floor(random() * 900000 + 100000)::int,
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3',
  'Digital Marketing Specialist | Content Creator | Coffee Enthusiast ☕ | Sharing tips tentang digital marketing, branding, dan social media strategy. Hubungi untuk kolaborasi atau konsultasi.',
  'https://instagram.com/anitawijaya',
  'https://facebook.com/anitawijaya',
  'https://linkedin.com/in/anitawijaya',
  NULL,
  'https://tiktok.com/@anitawijaya',
  TRUE,
  '+6281234567890',
  'telegram',
  TRUE,
  TRUE
) RETURNING id, name, username, numeric_id;
